---
title: "HACKODS"
author: "Los cuadernos"
date: last-modified
lang: es
format:
  html:
    fontsize: 20pt
    theme: 
      light: lumen
      dark: darkly
    embed-resources: true
    toc: true
    toc-location: left-body
    title-block-banner: "#6ca19e" 
    title-block-banner-color: "#fff"
    code-fold: true
    grid:
      body-width: 1200px
    fig-format: svg
execute:
  echo: false   
  warning: false
  message: false
---
# La escasez de agua en México

El agua es un recurso esencial para la vida, pero su disponibilidad y calidad están siendo amenazadas por diversos factores, como el cambio climático, la contaminación y el crecimiento demográfico. En este cuaderno, exploraremos los desafíos que enfrenta el agua a nivel país y estado, así como las posibles soluciones para garantizar su acceso sostenible para las generaciones futuras.


### Análisis de Vulnerabilidad
{{< embed notebook\003_Analisis_vulnerabilidad.ipynb#pruebaA >}}
### Acuíferos críticos
{{< embed notebook\003_Analisis_vulnerabilidad.ipynb#AcuiferosCriticos >}}
### Priorización de intervencion
{{< embed notebook\003_Analisis_vulnerabilidad.ipynb#PriorizacionIntervencion >}}
### Relacion Disponibilidad e Infraestructura
{{< embed notebook\003_Analisis_vulnerabilidad.ipynb#relacion >}}
### Acuiferos con dispionibilidad pero baja infraestructura
{{< embed notebook\003_Analisis_vulnerabilidad.ipynb#AcuiferosDisponibilidadBajaInfraestructura >}}
### Mapeo de resitrcciones legales en zonas criticas
{{< embed notebook\003_Analisis_vulnerabilidad.ipynb#MapeoRestriccionesLegales >}}

# Mapas
### MAPA 1: DISPONIBILIDAD DE AGUA SUBTERRÁNEA A NIVEL NACIONAL
{{< embed notebook\004_Atlas_cartografico.ipynb#Mapa1 >}}

### MAPA 2: BRECHA DE INFRAESTRUCTURA
{{< embed notebook\004_Atlas_cartografico.ipynb#Mapa2 >}}

### MAPA 3: RESTRICCIONES LEGALES DE EXTRACCIÓN (ZONAS DE VEDA)
{{< embed notebook\004_Atlas_cartografico.ipynb#Mapa3 >}}

# Soluciones
### Impacto de estrategia hidrica 
{{< embed notebook\005_simulacion_solucion.ipynb#Estrategia >}}
### Transición de Infraestructura Hídrica: Impacto de Política 2024-2030
{{< embed notebook\005_simulacion_solucion.ipynb#MapaAnimado >}}